version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bida_postgres
    environment:
      POSTGRES_DB: bida_db
      POSTGRES_USER: bida_user
      POSTGRES_PASSWORD: bida_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - bida_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bida_user -d bida_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bida_backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bida_db
      SPRING_DATASOURCE_USERNAME: bida_user
      SPRING_DATASOURCE_PASSWORD: bida_password
      JWT_SECRET: your-256-bit-secret-key-here-change-in-production
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bida_network
    volumes:
      - ./backend/src/main/resources:/app/resources:ro
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  bida_network:
    driver: bridge
