name: core_data
description: "Data layer and repositories for Billiard Club Management System"
version: 0.0.1

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP Client
  dio: ^5.4.3+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Core Domain
  core_domain:
    path: ../core_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
