spring:
  application:
    name: bida-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bida_db
    username: bida_user
    password: bida_password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # Flyway Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # WebSocket Configuration
  websocket:
    allowed-origins: "*"
  
  # Jackson Configuration
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-here-change-in-production
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.acme.bida.controller

# Logging Configuration
logging:
  level:
    com.acme.bida: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/bida_dev
    username: bida_dev_user
    password: bida_dev_password

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bida_prod}
    username: ${DB_USERNAME:bida_prod_user}
    password: ${DB_PASSWORD:bida_prod_password}
  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET:your-production-secret-key-here}
